spring:
  application:
    # 配置中心+注册中心
    name: SeirMeng-test
  datasource:
    url: jdbc:mysql://localhost:3306/db_zx_guarantee?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # json的全局配置
  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat

server:
  port: 18082
  servlet:
    context-path: /SeirMeng-test

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
