spring:
  application:
    # 配置中心+注册中心
    name: SeirMeng-edcation
  datasource:
    url: jdbc:mysql://localhost:3306/seirmeng_haidong_edu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # json的全局配置
  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat

server:
  port: 18081
  servlet:
    context-path: /SeirMeng-education

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/**Mapper.xml

logging:
  level:
    com.haidong.SeirMeng.service.edu.controller.TeacherController: debug
    root: info
